version: '3.9'

networks: 
    tig-net:
        driver: bridge

volumes:
    tig-data:

services:
    influxdb:
        image: influxdb:1.8.6
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "YOUR_DATABASE"
            INFLUXDB_ADMIN_USER: "YOUR_DATABASE_ADMIN_USER"
            INFLUXDB_ADMIN_PASSWORD: "YOUR_DATABASE_ADMIN_PASSWORD"
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/influxdb
        restart: always

    grafana:
        image: grafana/grafana:7.5.9
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: YOUR_GRAFANA_ADMIN_USER
            GF_SECURITY_ADMIN_PASSWORD: YOUR_GRAFANA_ADMIN_PASSWORD
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/grafana
        restart: always        

    telegraf:
        image: telegraf:1.19.0
        depends_on: 
            - "influxdb"
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "YOUR_DATABASE"
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
        tty: true
        networks: 
            - tig-net
        privileged: true
        restart: always
